spring.application.name=SpringBootWebFlux_Assign2_Pirawich_Patadee

logging.level.org.springframework=error
logging.level.com=trace
server.port=8084
spring.mongodb.host=localhost
spring.mongodb.port=27017
#port for mongdo db..
spring.mongodb.database=humber

